name: Python Wheels

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:

  build_wheels:
    name: ${{ github.workflow }} Python build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create wheel
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install "wheel" "setuptools>=42" "versioneer[toml]" "numpy>=1.6"
          python -m pip wheel -w wheelhouse .

      - uses: actions/upload-artifact@v4
        with:
          name: array_split-artifact-wheel
          path: ./wheelhouse/array_split*.whl
          retention-days: 10

  build_sdist:
    name: Build python sdist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install sdist build dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install "setuptools>=42" "versioneer[toml]" "numpy>=1.6"

      - name: Create python sdist
        run: python setup.py sdist --formats=gztar,zip

      - name: Upload python sdist
        uses: actions/upload-artifact@v4
        with:
          name: array_split-artifact-sdist
          path: ./dist/array_split*

  release:
    name: Make a Release
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download python sdist and wheels
        uses: actions/download-artifact@v4
        with:
          pattern: array_split-artifact-*
          path: ./release_artifacts/
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release_artifacts/*

  pypi_publish:
    name: Upload release to PyPI
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/array-split
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download python sdist and wheels
        uses: actions/download-artifact@v4
        with:
          pattern: array_split-artifact-*
          path: ./release_artifacts/
          merge-multiple: true

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./release_artifacts/
